backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: ../../static/img

collections:
  - name: "captcha"
    label: "Captcha"
    extension: "md"
    folder: "content/captcha"
    create: true
    editor:
      preview: true
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "string",
          hint: 'This is what will be displayed as prompt text. E.g. "Feet" -> "Please select all squares with Feet"',
          required: true,
        }
      - {
          label: "Order Priority",
          name: "priority",
          value_type: "int",
          widget: "number",
          hint: "Captcha puzzles appear in order from lowest to highest.",
          required: true,
          default: 0,
        }
      - label: "Images"
        name: "images"
        min: 1
        max: 9
        hint: "If less than nine images a specified, then random ones will be used to fill the difference."
        widget: "list"
        fields:
          - {
              label: "Image",
              name: "image",
              widget: "image",
              hint: "Please try to keep below ~200kb! https://tinypng.com/ is a great tool for image compression.",
              required: true,
              default: "",
              choose_url: false,
            }
          - {
              label: "Is Correct",
              name: "correct",
              widget: "boolean",
              hint: "Whether or not this option is required to be selected to advance.",
              required: true,
              default: false,
            }
  - name: "randomImages"
    label: "Random Images"
    extension: "md"
    folder: "content/randomImages"
    create: true
    editor:
      preview: false
    fields:
      - {
          label: "Title",
          name: "title",
          widget: "hidden",
          default: "collection",
        }
      - label: "Images"
        hint: "Pick which images are eligible to be picked at random to fill out other puzzles."
        name: "images"
        widget: "list"
        fields:
          - {
              label: "Image",
              name: "image",
              widget: "image",
              hint: "Please try to keep below ~200kb! https://tinypng.com/ is a great tool for image compression.",
              required: true,
              default: "",
              choose_url: false,
            }
          - {
              label: "Is Correct",
              name: "correct",
              widget: "hidden",
              default: false,
              step: 10,
            }
